import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { useUsersQuery } from '../generated/graphql';

const inter = Inter({ subsets: ['latin'] });

export const Home = () => {
  const [{ data }] = useUsersQuery();
  console.log(data);
  const onClick = async () => {
    console.log('onClick');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button {...{ onClick }}>Button</button>
      </main>
    </>
  );
};

export default Home;
